set -g default-terminal "xterm-256color"
set -g default-command zsh
#osx 
if-shell "uname | grep -q Darwin" "set-option -g default-command 'reattach-to-user-namespace -l zsh'";
if-shell "uname | grep -q Darwin" "set -g mouse on";


set -g status-right "#H %H:%M"
# set -g bell-action none
# set -g lock-after-time 1800
set -g status-bg colour232
set -g status-fg default
set-window-option -g window-status-current-bg colour233
set-window-option -g window-status-current-fg colour24
set-window-option -g automatic-rename on
set-option -g set-titles on

set -g remain-on-exit off
# setw -g window-status-current-attr "underscore"
#setw -g xterm-keys on
#
set -g status-keys vi

setw -g mode-keys vi
setw -g monitor-activity on

bind-key v split-window -h
bind-key s split-window -v
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

set -sg escape-time 0
bind r source-file ~/.tmux.conf

