source-file ~/.tmux/reset

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-boot 'on'
set -g @continuum-restore 'on'


set -g @resurrect-strategy-vim 'session'


set -g default-terminal "xterm-256color"
# set -g default-command zsh
set -g bell-action none
# set -g visual-bell off

# CLIPBOARD
set -g mouse on
set -g set-clipboard off
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -se c -i"

#osx 
# if-shell "uname | grep -q Darwin" "set-option -g default-command 'reattach-to-user-namespace -l zsh'";
# if-shell "uname | grep -q Darwin" "set -g mouse on";

set -g remain-on-exit off
setw -g xterm-keys on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000
set -g status-keys vi
setw -g mode-keys vi
setw -g monitor-activity off

# STATUS AND COLORS 
# set -g bell-action none
# set -g lock-after-time 1800
set -g status-left ""
set -g status-bg colour233
set -g status-fg default
set -g status-right "#H %H:%M"
# set-option -g status-right "#[fg=blue,bright]#(gcalcli --nocolor agenda --military --nostarted | head -2 | tail -1)#[default]"

# set -g status-right "#{?pane_synchronized, #[bg=blue]SYNCHRONIZED#[default],} #S "
 
# Window list.
# setw -g window-status-fg colour124 # grey
# setw -g window-status-bg black
# setw -g window-status-attr none
# setw -g window-status-format "#[fg=colour239]#I#[fg=colour240] #W "
# be sure to see note* below
# set-option -g automatic-rename on
# set-option -g automatic-rename-format '#{b:pane_current_path} #{pane_current_command}'
# set-window-option -g window-status-current-format '#[fg=white,bold]** #{window_index} #[fg=green]#{pane_current_command} #[fg=blue]#(echo "#{pane_current_path}" | rev | cut -d'/' -f-3 | rev) #[fg=white]**|'
set-window-option -g window-status-current-format '#[fg=white,bold]#{window_index} #[fg=red]#{pane_current_command} #[fg=blue]#{b:pane_current_path} #[fg=colour235]|'
set-window-option -g window-status-format '#[fg=white,bold]#{window_index} #[fg=colour23]#{pane_current_command} #[fg=blue]#{b:pane_current_path} #[fg=colour235]|'



# status bar updates every 15s by default**, change to 1s here
# (this step is optional - a lower latency might have negative battery/cpu usage impacts)
setw -g status-interval 7
 
# Active window.
# setw -g window-status-current-fg colour24 
# setw -g window-status-current-bg black
# setw -g window-status-current-attr bright
# setw -g window-status-current-format "#[fg=colour172]#I#[fg=white] #W#F"
 
# Window activity.
# setw -g window-status-activity-fg colour246 # grey
# setw -g window-status-activity-bg black

set-window-option -g automatic-rename on
set-option -g set-titles on

# BINDINGS
set-option -g prefix M-u
set -sg escape-time 0

bind-key v split-window -h
bind-key s split-window -v
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R
bind C-t next-window
# unbind n
# bind n new-window
 bind h previous-window
 bind l next-window
bind Down resize-pane -D 10
bind Up resize-pane -U 10
bind Left resize-pane -L 10
bind Right resize-pane -R 10
bind r source-file ~/.tmux.conf



# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
