# profile=opengl-hq
# deband=no

# scale=ewa_lanczossharp
# cscale=ewa_lanczossoft

# Interpolation (a.k.a. smoothmotion) related settings
# interpolation
# tscale=catmull_rom  # $ mpv tscale=help for possible options
#tscale=oversample
# tscale=mitchell
#temporal-dither
# video-sync=display-resample


#blend-subtitles=yes
save-position-on-quit


slang=fr,fra,fre,french,enUS,en,eng,ptBR,pt
alang=jp,jpn,enUS,en,eng,fr,fra,fre

#input-ipc-server=/tmp/mpvsocket
#hwdec-codecs=all
#hwdec=auto-copy

#osd-font-size=14

# hwdec=no
# opengl-early-flush=no
# vf=vapoursynth=~/.config/mpv/mvtools.vpy
# vf=vapoursynth=~/.config/mpv/test.vpy:60:4
#sub-delay=0.3

sub-font-size=48
sub-pos=90
