return {
  {"mustache/vim-mustache-handlebars",
   ft = {"mustache", "handlebars", "hbs", "html.hbs", "html.handlebars", "html.mustache"}
  },
  {"chr4/nginx.vim",
      ft = {"nginx"},
  },
  {"wgwoods/vim-systemd-syntax",
    ft = {"systemd"},
  },
  {"digitaltoad/vim-pug",
    ft = {"pug", "jade"},
  },
  {"hjson/vim-hjson",
    ft = {"hjson"},
  },
  {"Fymyte/rasi.vim",
    ft = {"rasi"},
  },
  {"nfnty/vim-nftables",
    ft = {"nftables"},
  },
  {"Glench/Vim-Jinja2-Syntax",
    ft = {"jinja"},
  },
  {"terrastruct/d2-vim",
    ft = {"d2"},
  },
  {"https://github.com/joerdav/templ.vim" }
}
