profile=gpu-hq
fs=yes
# keep-open=yes
save-position-on-quit

audio-channels=stereo
slang=fr,fra,fre,french,enUS,en,eng
alang=jp,jpn,enUS,en,eng,fr,fra,fre

ao=pulse
hr-seek-framedrop=no
#input-ipc-server=/tmp/mpvsocket


opengl-early-flush=no
# VIDEO FILTERS
# vf=@interpolation:vapoursynth=~/.config/mpv/mvtools.vpy
#hwdec=no
# vf=@interpolation:!vapoursynth=~/.config/mpv/mvtools3.py
# vf=@denoiser:!vapoursynth=~/.config/mpv/denoise.py



# AUDIO FILTERS
# af=@normalize:lavfi="[alimiter=8:1:1:5:100]"
af=@normalize:!lavfi="loudnorm"
# vf=vapoursynth=~/.config/mpv/test.vpy:60:4

blend-subtitles=no
sub-ass-override=strip
osd-scale-by-window=no
osd-font-size=54
sub-scale-by-window=no
sub-font-size=90
sub-pos=100
# hdr-compute-peak=no

#sub-delay=0.3
ytdl=yes


screenshot-directory=~/Bureau/
